# Generated by Django 3.1.1 on 2020-10-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
