# Generated by Django 3.1.1 on 2020-10-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_poems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poems',
            new_name='Poem',
        ),
    ]
