# Generated by Django 3.1.2 on 2020-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0007_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='cover_image',
            field=models.ImageField(default='stock.jpg', upload_to='images/'),
        ),
    ]
