# Generated by Django 3.1.2 on 2020-10-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0008_poem_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='cover_image',
            field=models.ImageField(default='images/stock.jpg', upload_to='images/'),
        ),
    ]
